[build]
  publish = "public"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/get-key"
  to = "/get-key.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
