// Optional mirror of sign-ups into an Oracle database (e.g. one on your own PC, managed with
// Oracle SQL Developer). SQLite stays the primary store; if the Oracle side is unreachable the
// web app keeps working and the failure is only logged.
//
// Enabled when ORACLE_USER, ORACLE_PASSWORD and ORACLE_CONNECT_STRING are all set,
// e.g. ORACLE_CONNECT_STRING=100.64.0.5:1521/XEPDB1 (Tailscale IP of the PC : port / service name)
const oracledb = require("oracledb"); // thin mode: no Oracle Client install needed

const { ORACLE_USER, ORACLE_PASSWORD, ORACLE_CONNECT_STRING } = process.env;
const enabled = !!(ORACLE_USER && ORACLE_PASSWORD && ORACLE_CONNECT_STRING);

let poolPromise = null;
function getPool() {
  if (!poolPromise) {
    poolPromise = oracledb
      .createPool({
        user: ORACLE_USER,
        password: ORACLE_PASSWORD,
        connectString: ORACLE_CONNECT_STRING,
        poolMin: 0,
        poolMax: 3,
        queueTimeout: 30000,
        transportConnectTimeout: 8, // seconds; fail with a clear network error instead of a queue timeout
      })
      .then(async (pool) => {
        await ensureSchema(pool);
        return pool;
      })
      .catch((e) => {
        poolPromise = null; // retry on the next sign-up
        throw e;
      });
  }
  return poolPromise;
}

const DDL = [
  `CREATE TABLE app_users (
      id NUMBER PRIMARY KEY,
      username VARCHAR2(100) NOT NULL UNIQUE,
      email VARCHAR2(255),
      role VARCHAR2(30),
      provider VARCHAR2(20),
      provider_id VARCHAR2(100),
      created_at TIMESTAMP
  )`,
  `CREATE TABLE app_registrations (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      username VARCHAR2(100),
      method VARCHAR2(20) NOT NULL,
      ip_address VARCHAR2(45),
      user_agent VARCHAR2(300),
      created_at TIMESTAMP
  )`,
];

async function ensureSchema(pool) {
  const conn = await pool.getConnection();
  try {
    for (const ddl of DDL) {
      try {
        await conn.execute(ddl);
      } catch (e) {
        if (e.errorNum !== 955) throw e; // ORA-00955: table already exists
      }
    }
  } finally {
    await conn.close();
  }
}

// Fire-and-forget: never throws, never blocks the sign-up response.
function mirrorRegistration(user, reg) {
  if (!enabled) return;
  (async () => {
    const pool = await getPool();
    const conn = await pool.getConnection();
    try {
      await conn.execute(
        `INSERT INTO app_users (id, username, email, role, provider, provider_id, created_at)
         VALUES (:id, :username, :email, :role, :provider, :provider_id, :created_at)`,
        {
          id: user.id,
          username: user.username,
          email: user.email || null,
          role: user.role,
          provider: user.provider || "local",
          provider_id: user.provider_id || null,
          created_at: new Date(user.created_at),
        }
      );
      await conn.execute(
        `INSERT INTO app_registrations (user_id, username, method, ip_address, user_agent, created_at)
         VALUES (:user_id, :username, :method, :ip, :ua, :created_at)`,
        {
          user_id: user.id,
          username: user.username,
          method: reg.method,
          ip: reg.ip || null,
          ua: reg.userAgent || null,
          created_at: new Date(reg.createdAt),
        }
      );
      await conn.commit();
    } finally {
      await conn.close();
    }
  })().catch((e) => console.error("[oracle] sign-up mirror failed:", e.message));
}

// Connect and create the tables at boot, so problems show up in the log right away.
// Retries a few times because the Tailscale link may come up after the app starts.
function connectAtStartup(attempt = 1) {
  getPool()
    .then(() => console.log("[oracle] connected, tables ready"))
    .catch((e) => {
      console.error(`[oracle] startup connection failed (attempt ${attempt}):`, e.message);
      if (attempt < 6) setTimeout(() => connectAtStartup(attempt + 1), 15000).unref();
    });
}
if (enabled) connectAtStartup();

module.exports = { mirrorRegistration, enabled };
